title: Siac Scrapping Sync - v1.1.3
base_url: https://alunoweb.ufba.br/SiacWWW/
completed_courses_url: https://alunoweb.ufba.br/SiacWWW/ConsultarCoeficienteRendimento.do
log:
    dir: logs/logs
    general_log_file: general_log
    return_log_file: return_log
    log_file_extension: .log
notion:
    button_text: Authenticate
    config_fields:
    - Notion Token
    - Main Database ID
    - Rejection Database ID
    url: https://api.notion.com/v1
notion_login:
    token: ''
    main_db_id: ''
    rr_db_id: ''
siac:
    login: null
    password: null
    login_url: https://alunoweb.ufba.br/SiacWWW/Welcome.do
timeout:
    element: 10
    page_load: 20
webdriver:
    driver_path: drivers/chromedriver
    headless: true
